# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.CharField(blank=True, max_length=100)),
                ('y_axis', models.CharField(blank=True, max_length=100)),
                ('querystring', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='Query',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='mainsite.Dashboard'),
        ),
    ]
