# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='chart_type',
            field=models.IntegerField(choices=[(0, 'Table'), (1, 'Line'), (2, 'Bar')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_set', to='mainsite.Dashboard'),
        ),
    ]
