# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20161206_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('database_type', models.CharField(max_length=100)),
                ('database_name', models.CharField(blank=True, max_length=100)),
                ('database_host', models.CharField(blank=True, max_length=100)),
                ('database_port', models.IntegerField(blank=True, null=True)),
                ('database_username', models.CharField(blank=True, max_length=100)),
                ('database_password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='query',
            name='chart_type',
            field=models.IntegerField(choices=[(0, 'Table'), (1, 'Line'), (2, 'Bar')], default=0),
        ),
        migrations.AddField(
            model_name='query',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Database'),
        ),
    ]
