# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 02:29
from __future__ import unicode_literals

from django.db import migrations

forward_sql = '''
CREATE UNIQUE INDEX unique_database_name on mainsite_database (database_name);
'''

backward_sql = '''
DROP UNIQUE INDEX unique_database_name;
'''

class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20161211_0108'),
    ]

    operations = [
        migrations.RunSQL(forward_sql, backward_sql)
    ]
